### ISSUE TITLE
BotorchRecommender not available?

### ISSUE THREAD

**Issue by dpersaud** [emdgroup/baybe#312] opened 2024-07-13 04:10 UTC
Hi, i was working through the example on this packages home page and it seems the 'BotorchRecommender' is not available in baybe.recommenders.

**Comment by Scienfitz** [comment] 2024-07-14 19:37
Hey @dp, 

please make sure you use the right version of baybe that is compatible with the source where you draw the examples from.

For instance:
- The code you see in the github repo readme is for the latest main version, which will almost always not correspond to the latest version on PyPI
- The code you see in the documentation is for the last PyPI version, but lacks all unpublished updates done since then (such as the renaming affecting the recommender in your case)

We will soon have a multiversion documentation, where it will be clearer to which version the code you're viewing belongs and where you can also select a specific version if desired.

**Comment by Scienfitz** [comment] 2024-07-17 22:35
Closing as it was confirmed fixed by @dpersaud in meeting

**Closed by Scienfitz** 2024-07-17 22:35 UTC
Labels: question, wontfix
