### ISSUE TITLE
ModuleNotFoundError: No module named 'baybe.objectives'

### ISSUE THREAD

**Issue by rickwierenga** [emdgroup/baybe#229] opened 2024-05-03 00:13 UTC
Steps to reproduce:

```sh
pip install baybe
python -c "from baybe.objectives import SingleTargetObjective"
```

(from README)

i do see the module in the repo, but it appears it's not packaged in the version on PyPI?

**Comment by AdrianSosic** [comment] 2024-05-03 05:49
HI @rickwierenga, we are aware of this problem, which is due to a desync between the docs and the released PyPI versions. In particular, the issue is a duplicate of #222, therefore I'll close this thread. But nevertheless: thanks for taking to time to report 🎖️ 

@Scienfitz, @AVHopp: Unsurprisingly, reports keep piling up, since literally **everyone** who uses `baybe` for the first time **will** run into this issue. Since it's now already been a week since we spoke about it + next week is short and I'm OOO today + I'm 100% sure that 0.9.0 will not be released within the next 10 days, could you do me a favor: 
* Create a small hotfix PR that activates the `--force` option for the docs (no changelog etc needed)
* Trigger the doc building on the current `main`

That way, have at least a temporary fix until the multiversion doc is ready. Thx 🙃

**Closed by AdrianSosic** 2024-05-03 05:49 UTC
Labels: documentation, duplicate

**Comment by AdrianSosic** [comment] 2024-05-03 05:57
... and with `main` I actually meant latest PyPI version, of course, in order to resync 😄

**Comment by Scienfitz** [comment] 2024-05-03 06:06
@AdrianSosic I think it needs more than just the force option as you also need to control which branch is checked out, adding the force option is not sufficient because the pipeline on the existing tag isnt modified

**Comment by AdrianSosic** [comment] 2024-05-03 06:17
I think that shouldn't matter, because you can trigger the *new* pipeline on the *old* tag via the selector

**Comment by AdrianSosic** [comment] 2024-05-03 06:20
Or am I wrong?

**Comment by Scienfitz** [comment] 2024-05-03 06:22
are you sure? this reads different to me in the sense that it will check out the rag you select before running
![image](https://github.com/emdgroup/baybe/assets/17951239/bf357636-c2ab-4b7e-b597-d4b65ab2fb25)

bt i can simply add an option to i) fore and ii) optionally select a tag too be able to publish tags of the past

**Comment by AdrianSosic** [comment] 2024-05-03 06:40
Or even simpler: you can simply test it on your fork upfront and then we know 🙃

**Comment by Scienfitz** [comment] 2024-05-03 06:41
already running

**Comment by AVHopp** [comment] 2024-05-03 07:34
If I interpret the documentation correctly, it is now at 0.8.2 again right?

**Comment by Scienfitz** [comment] 2024-05-03 07:43
@AVHopp yes

@AdrianSosic 
what you suggest is not possible, hence I added options to control behavior now. You can run the action from main (old action versions are not affected), but checkout a previous tag + force or not 
![image](https://github.com/emdgroup/baybe/assets/17951239/9405da99-0a1e-42bb-b9e2-5fcc8be4a589)
