### ISSUE TITLE
Simulation bug in `ignore` mode

### ISSUE THREAD

**Issue by brandon-holt** [emdgroup/baybe#200] opened 2024-04-09 16:17 UTC
Hello! I get an error when trying to run simulate_experiment. The code errors here in simulation.py

```python    if impute_mode == "ignore":
        searchspace = campaign.searchspace.discrete.exp_rep
        missing_inds = searchspace.index[
            searchspace.merge(lookup, how="left", indicator=True)["_merge"]
            == "left_only"
        ]
        campaign.searchspace.discrete.metadata.loc[
            missing_inds, "dont_recommend"
        ] = True
```

The error is `IndexError: boolean index did not match indexed array along dimension 0; dimension is 131220 but corresponding boolean dimension is 131227`

I'm a bit confused since the error happens because the length of the `missing_inds` and `campaign.searchspace.discrete.metadata` don't match up, but they are both derived from `campaign.searchspace.discrete`?

What might be going on here?

**Comment by Scienfitz** [comment] 2024-04-09 16:57
hey, no idea what could have gone wrong if you dont also include the lines how you've called the function and prepared the campaign. Can you post this?

**Comment by brandon-holt** [comment] 2024-04-09 17:43
@Scienfitz Totally, my apologies! 

```python
from baybe.targets import NumericalTarget, TargetMode
from baybe.objective import Objective
from baybe.parameters import NumericalDiscreteParameter, SubstanceParameter
from baybe.targets import TargetTransformation
from baybe import Campaign
from baybe.searchspace import SearchSpace
from baybe.recommenders import (
    SequentialGreedyRecommender,
    RandomRecommender,
    TwoPhaseMetaRecommender,
)
from baybe.searchspace.discrete import SubspaceDiscrete
from baybe.simulation import simulate_experiment
import pandas as pd

target = NumericalTarget(
    name="Pass QC",
    mode=TargetMode.MAX,
    bounds=(0, 1),
    transformation=TargetTransformation.LINEAR,
)

objective = Objective(mode="SINGLE", targets=[target])

molecule_df = pd.read_csv("molecules.csv")
molecule_types = ['typeA', 'typeB', 'typeC', 'typeD'] 
molecules = {
    molecule_type: dict(
        zip(
            molecule_df[molecule_df["type"] == molecule_type]["molecule_name"],
            molecule_df[molecule_df["type"] == molecule_type]["smiles"],
        )
    )
    for molecule_type in molecule_types
}

data = load_data()
# data loaded from a csv, columns are features, with target value as last column
# data excerpt shown below

substance_parameters = [
    SubstanceParameter(
        name=molecule_type,
        data=molecules[molecule_type]
    )
    for molecule_type in molecule_types
]

# here I construct the discrete search space by only using values found in the dataset (if there is a better way to do this happy to hear)
discrete_parameters = [NumericalDiscreteParameter(name=f"{molecule_type} Mole", values=sorted(data[f"{molecule_type} Mole"].unique()))
    for molecule_type in molecule_types
]

searchspace = SearchSpace(
    discrete=SubspaceDiscrete.from_simplex(
        max_sum=100,
        simplex_parameters=discrete_parameters,
        product_parameters=substance_parameters,
        boundary_only=True
    )
)

recommender = TwoPhaseMetaRecommender(
    initial_recommender=RandomRecommender(),  # Random search
    recommender=SequentialGreedyRecommender(),  # Bayesian model-based optimization
)

campaign = Campaign(searchspace, objective, recommender)

results = simulate_experiment(
    campaign,
    data,
    batch_size=10,
    random_seed=1,
    impute_mode='ignore'
)
```


Here is an example head from the data table, in reality it has hundreds to thousands of rows.


<head>





</head>

<body link="#467886" vlink="#96607D">


typeA | typeB | typeC | typeD | typeA Mole | typeB Mole | typeC Mole | typeD Mole | Pass QC
-- | -- | -- | -- | -- | -- | -- | -- | --
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_02 | molecule_04 | molecule_05 | 35 | 15 | 2.5 | 47.5 | 1
molecule_01 | molecule_03 | molecule_04 | molecule_05 | 35 | 30 | 2.5 | 32.5 | 1
molecule_01 | molecule_03 | molecule_04 | molecule_05 | 35 | 35 | 2.5 | 27.5 | 1



</body>

</html>

**Comment by AdrianSosic** [comment] 2024-04-10 06:29
Hi @brandon-holt, thanks for the detailed error report 🥇 There is no obvious problem that I can spot immediately, but I'm happy to investigate. Will try to reproduce the error on my machine. In case I struggle to reproduce, I'll reach out again.

Two comments upfront:
* I guess "QC" stands for "quality control", which suggest to me that your target is really a binary variable here? I think modeling it as a `NumericalTarget` is fine since you only have one such target. But I still wanted to let you know that categorical targets are already on our roadmap 🎯 
* The `simulation` module is still one of our legacy modules for which a refactoring is overdue and already planned. So it could be absolutely the case that you are running into some form of edge case here. I think we should be able to figure it out ✌🏼

**Comment by brandon-holt** [comment] 2024-04-10 10:49
@AdrianSosic Yes absolutely, will do! Just will take some time because I am OOO today and will also need to take some time to recreate with private data stripped. Thanks for all your help!

**Comment by brandon-holt** [comment] 2024-04-11 16:02
@AdrianSosic Here you go, here's a kit to reproduce the error I'm seeing! If you run sim_bug_repro.py, you should get `IndexError: boolean index did not match indexed array along dimension 0; dimension is 1428840 but corresponding boolean dimension is 1428879`

I am running Python 3.11.8. Please let me know if you need any other info to reproduce the error, or have questions about the code!

Thanks :)

[sim_bug_repro.zip](https://github.com/emdgroup/baybe/files/14948482/sim_bug_repro.zip)

**Comment by AdrianSosic** [comment] 2024-04-12 07:03
Hi @brandon-holt, perfect, thanks for sharing 👍🏼 I just had a look and found the issue quickly, it's really a (rather common) case that we somehow forgot to consider in the simulation code: your lookup data contains "semi-duplicates", i.e. rows that contain identical parameter configurations but with different values for the target variable. "Pure" duplicates wouldn't have been a problem because the merge automatically takes care of that. However, if the targets differ, the question arises what should actually happen in the simulation. 

My first thought is that we need to specify an additional resolution mechanism, i.e. similar to the `impute_mode` for missing lookup values, we could have a `duplicate_mode` that dictates how to handle duplicate entries. And choices could be something like:
* `random`, where in each iteration a random row will be selected (mimicking what would happen in a real-world run)
* `mean`, where the duplicate target values get averaged before the simulation
* callable, where the user provides a custom resolution strategy in form of a callable
* ...

I'll discuss this with the dev team but would also like to hear your opinion on it 🙃

**Comment by Scienfitz** [comment] 2024-04-12 08:51
@AdrianSosic the lookup of the actual values arleady incorporates that possibility, see:
```python
            if len(ind) > 1:
                # More than two instances of this parameter combination
                # have been measured
                _logger.warning(
                    "The lookup rows with indexes %s seem to be "
                    "duplicates regarding parameter values. Choosing a "
                    "random one.",
                    ind,
                )
                match_vals = lookup.loc[np.random.choice(ind), target_names].values
```
in simulation.py

But it seems the pre-filtering in case if `ignore` impute option is chosen does not account for that causing semi-duplicates to change the index length:
![image](https://github.com/emdgroup/baybe/assets/17951239/0aef9a42-9303-4eca-ae20-937b683cf6d1)

Since the merge will result in duplciate rows, we could just drop duplicates, no other change would be neede
```python
        missing_inds = searchspace.index[
            searchspace.merge(lookup, how="left", indicator=True).drop_duplicates().set_index(searchspace.index)["_merge"]
            == "left_only"
        ]
```
resulting in 
![image](https://github.com/emdgroup/baybe/assets/17951239/10234b40-13a1-4fd7-9f1f-bb5a3eef4d22)

**Comment by AdrianSosic** [comment] 2024-04-12 10:42
Hi @brandon-holt. So the error is now fixed on the `main` branch. If you run a
```bash
pip install git+https://github.com/emdgroup/baybe.git@main
```
the simulation should work 👍🏼 An upcoming release is also on the horizon, probably next week.

That said, I only implemented the hotfix for now but *not* the `duplicate_mode` option because – as @Scienfitz correctly pointed out – the most basic case (`random`) is already happening automatically in the code. In fact, you'll see some warnings when you run the code that inform you about your duplicates. 

Nonetheless, the bigger simulation refactoring is still pending and we can extend the logic there. Happy to hear your thoughts/wishes!

**Closed** 2024-04-12 10:42 UTC
Labels: bug

**Comment by AdrianSosic** [comment] 2024-04-12 11:00
@brandon-holt, perhaps one other unrelated comment:

I noticed that you are modeling some form of mixture and you are using the "slot-based" representation to describe your search space (i.e. field containing the substance + field containing the abundance) but as far as I can see you are not dealing with the issue of permutation invariance. 

For the simulation example in `ignore` mode it doesn't really matter since permuted search space elements will automatically be dropped (due having no match in the lookup) but for an actual DOE loop this would cause a problem since the model would not be aware of the invariance. I suggest to have a look [here](https://emdgroup.github.io/baybe/userguide/constraints.html#discretepermutationinvarianceconstraint) ;)

**Comment by brandon-holt** [comment] 2024-04-12 11:43
@AdrianSosic @Scienfitz Thank you both this is awesome!!

Regarding the DiscretePermutationInvarianceConstraint, thank you so much for pointing me towards that, and indirectly towards the examples on using mixtures. This is exactly what I need to be using :) 

Regarding the options for "semi-duplicate" resolution, I think random and mean probably cover 90+% of cases and callable takes care of the rest. 

If I had to think of other options I might suggest "mode" for discrete targets which picks the output that occurs most frequently. 

Another could be "recent" which picks the most recent (by row index) since data like this is usually appended over time, and some users might just want to use the most recent data points as the ones they trust more for empirical reasons.

Again, thanks so much for being so on top of things, you all have built something really awesome!!!
